name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ vars.CLOUD_RUN_SERVICE_NAME }}
  IMAGE: us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.CLOUD_RUN_SERVICE_NAME }}/${{ vars.CLOUD_RUN_SERVICE_NAME }}

jobs:
  build-and-push:
    name: Build and push
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Cloud Run
    environment: production
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ env.IMAGE }}:${{ github.sha }}
          service: ${{ env.SERVICE_NAME }}
          region: us-central1
